### ISSUE TITLE
Issue with subprocess ping

### ISSUE THREAD

**Issue by cthoyt** [scolby33/OCSPdash#4]
I'm pretty sure you're supposed to give all the stuff for subprocess.run as a list and not a string. Check https://docs.python.org/3/library/subprocess.html#subprocess.run

```
$ python3 -m ocspdash update -v
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.censys.io
DEBUG:urllib3.connectionpool:https://www.censys.io:443 "GET /api/v1/account HTTP/1.1" 200 237
DEBUG:urllib3.connectionpool:https://www.censys.io:443 "POST /api/v1/report/certificates HTTP/1.1" 200 702
DEBUG:ocspdash.util:throttling 4.296289s... 
DEBUG:urllib3.connectionpool:https://www.censys.io:443 "POST /api/v1/report/certificates HTTP/1.1" 200 455
DEBUG:ocspdash.server_query:Getting raw certificates for Let's Encrypt: http://ocsp.int-x3.letsencrypt.org/
DEBUG:ocspdash.server_query:Getting example cert for Let's Encrypt: http://ocsp.int-x3.letsencrypt.org/
DEBUG:urllib3.connectionpool:https://www.censys.io:443 "POST /api/v1/search/certificates HTTP/1.1" 200 194183
DEBUG:ocspdash.server_query:Getting issuer cert for Let's Encrypt: http://ocsp.int-x3.letsencrypt.org/
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): cert.int-x3.letsencrypt.org
DEBUG:urllib3.connectionpool:http://cert.int-x3.letsencrypt.org:80 "GET / HTTP/1.1" 200 1174
DEBUG:urllib3.connectionpool:https://www.censys.io:443 "POST /api/v1/report/certificates HTTP/1.1" 200 804
DEBUG:ocspdash.server_query:Pinging ocsp.int-x3.letsencrypt.org
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/cthoyt/dev/OCSPdash/src/ocspdash/__main__.py", line 10, in <module>
    main()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/cthoyt/dev/OCSPdash/src/ocspdash/cli.py", line 94, in update
    m.update(user)
  File "/Users/cthoyt/dev/OCSPdash/src/ocspdash/web/manager.py", line 164, in update
    result.ping = self.server_query.ping(parse_result.netloc)
  File "/Users/cthoyt/dev/OCSPdash/src/ocspdash/server_query.py", line 90, in ping
    return subprocess.run(f'ping {parameters} {host}', stdout=subprocess.DEVNULL).returncode == 0
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1333, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'ping -c 1 ocsp.int-x3.letsencrypt.org'
```

**Comment by cthoyt** [comment]
Should be solved, but we need to discuss first.

**Comment by scolby33** [comment]
Weird, it works on Windows.\* I'll try the new version and let you know.

\*Said no one ever.

**Comment by scolby33** [comment]
I can confirm that the new version works on Windows as well. Closing.
