### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by cthoyt** [scolby33/OCSPdash#5]
after running 25 long minutes I got this error...

```
DEBUG:urllib3.connectionpool:https://www.globalsign.com:443 "GET / HTTP/1.1" 403 None
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/cthoyt/dev/OCSPdash/src/ocspdash/__main__.py", line 10, in <module>
    main()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/cthoyt/dev/OCSPdash/src/ocspdash/cli.py", line 94, in update
    user = m.get_or_create_user('test')
  File "/Users/cthoyt/dev/OCSPdash/src/ocspdash/web/manager.py", line 165, in update
    result.ocsp = self.server_query.check_ocsp_response(chain.subject, chain.issuer, url)
  File "/Users/cthoyt/dev/OCSPdash/src/ocspdash/server_query.py", line 154, in check_ocsp_response
    parsed_ocsp_response = OCSPResponse.load(ocsp_resp.content)
  File "/usr/local/lib/python3.6/site-packages/asn1crypto/core.py", line 230, in load
    value, _ = _parse_build(encoded_data, spec=spec, spec_params=kwargs, strict=strict)
  File "/usr/local/lib/python3.6/site-packages/asn1crypto/core.py", line 5099, in _parse_build
    return (_build(*info, spec=spec, spec_params=spec_params), new_pointer)
  File "/usr/local/lib/python3.6/site-packages/asn1crypto/core.py", line 5008, in _build
    tag
ValueError: Error parsing asn1crypto.ocsp.OCSPResponse - tag should have been 16, but 28 was found
```

**Comment by scolby33** [comment]
Weird. That looks like the response you received from the OCSP server was invalid. I'll add a `try:...except ValueError` around that call and just fail the OCSP test if it can't be parsed.

**Comment by cthoyt** [comment]
does that error mean anything to you?

**Comment by scolby33** [comment]
P.S. this is why it'd be awesome if all functions documented what exceptions they might raise. Sometimes I think I might prefer Swift...

**Comment by cthoyt** [comment]
ugh... java does that too

but then again, nothing is stopping people from writing better documentation

**Comment by scolby33** [comment]
No, it's some issue with the ASN data structure of the response. I tried to understand ASN once, but it didn't work. It's some binary coding and all the definitions are like `thing:: = something[included by reference] blah blah` and it's too much.
